let employees = [
    {
        id: 001,
        name: 'Ирина',
        surname: 'Сахарова',
        dateBorn: '1990',
        photo: 'https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fpavelkrapivin%2Ffiles%2F2018%2F09%2FHappy-Employee-Working-Laptop-AdobeStock_171333654-by-By-Drobot-Dean-1200x801.jpg',
        city: 'СПб',
        street: 'пр. Просвещения',
        building: '',
        flat: '',
        workType: 'checked',
        position: ''
    },
    {
        id: 002,
        name: 'Петр',
        surname: 'Петров',
        dateBorn: '2000',
        photo: 'https://specials-images.forbesimg.com/imageserve/5d3d7a55f1176b000897d627/960x0.jpg?fit=scale',
        city: 'СПб',
        street: 'пр. Гражданский',
        building: '',
        flat: '',
        workType: 'checked',
        position: ''
    },
    {
        id: 003,
        name: 'Сергей',
        surname: 'Сидоров',
        dateBorn: '1976',
        photo: 'https://eloo.com.sa/wp-content/uploads/2019/10/Product_6.4.1_Employee_Stock_Ownership_Plans_Getty_109260481_994x630.jpg',
        city: 'СПб',
        street: 'пр. Гражданский',
        building: '',
        flat: '',
        workType: '',
        position: ''
    },
    {
        id: 004,
        name: 'Наталья',
        surname: 'Суслова',
        dateBorn: '1984',
        photo: 'https://www.unily.com/media/30012/employee-experience-reduce-turnover.jpg?width=1500&height=840&mode=crop',
        city: 'СПб',
        street: 'пр. Гражданский',
        building: '',
        flat: '',
        workType: '',
        position: ''
    },
    {
        id: 005,
        name: 'Алексей',
        surname: 'Петров',
        dateBorn: '1998',
        photo: 'https://i.nextmedia.com.au/Utils/ImageResizer.ashx?n=https%3A%2F%2Fi.nextmedia.com.au%2FNews%2F_DSC3139a_opt.jpg&w=480&c=0&s=1',
        city: 'СПб',
        street: 'пр. Гражданский',
        building: '255',
        flat: '',
        workType: '',
        position: ''
    },
    {
        id: 006,
        name: 'Алексей',
        surname: 'Терешков',
        dateBorn: '1995',
        photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT-Sm-Sav8EXs3x-j5Yxk55QoHcuNTayM4Q-YW1Dtuhkfma4_yF&usqp=CAU',
        city: 'СПб',
        street: 'пр. Гражданский',
        building: '255',
        flat: '',
        workType: '',
        position: ''
    },
    {
        id: 007,
        name: 'Александра',
        surname: 'Терешкова',
        dateBorn: '1995',
        photo: 'https://www.irishlifecorporatebusiness.ie/sites/default/files/slider/employee_2.jpg',
        city: 'СПб',
        street: 'пр. Гражданский',
        building: '255',
        flat: '',
        workType: 'checked',
        position: ''
    },
    {
        id: 010,
        name: 'Виктория',
        surname: 'Ларина',
        dateBorn: '1995',
        photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTk4eCcRGCNtKmmHJLdOyOVSLRiZewPizTWkZvfV8OTIybrHCO0&usqp=CAU',
        city: 'СПб',
        street: 'пр. Гражданский',
        building: '255',
        flat: '',
        workType: '',
        position: ''
    },
    {
        id: 011,
        name: 'Василий',
        surname: 'Новиков',
        dateBorn: '1991',
        photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSD62Drm3gL0rb9nzsoDWS0BEFaMOxMxgcOdMDEnL7EiXb0DjiL&usqp=CAU',
        city: 'СПб',
        street: 'пр. Просвещения',
        building: '10',
        flat: '147',
        workType: '',
        position: ''
    }
    
]